Initial development

diff --git a/bin/varsubst b/bin/varsubst
--- a/bin/varsubst
+++ b/bin/varsubst
@@ -1,50 +1,120 @@
 #!/bin/bash
-set -e -o pipefail
+#set -e -o pipefail
 
-passes=2
-filename=''
-verbose=0
-strict=0
-prefix=''
+function usage() {
+  [[ -z "$1" ]] || echo "$1" >&2
+  local exit_code=0
+  [[ -z "$2" ]] || exit_code="$2"
+  cat <<EOF
+USAGE: varsubst [OPTIONS] filename"
 
-  contents=$(<liquibase.properties)
-  contents_orig="$contents"
-  if [[ "$contents" ==  *'${'*'}'* ]]; then
-    echo "Replacing variables in liquibase.properties" >&2
-    vars=( URL DATABASE HOST PORT USERNAME PASSWORD CHANGELOG LOGLEVEL CLASSPATH DRIVER )
-    err=0
-    for var in "${vars[@]}"; do
-      lvar="LIQUIBASE_$var"
-      eval "val=\${$lvar:-NULL}"
-      varmatch='${'$var'}'
-      if [[ "$contents" == *"$varmatch"* ]]; then
-        if [[ "$val" == 'NULL' ]]; then
-          echo "\${$var} in liquibase.properties, but env var LIQUIBASE_$var was not set" >&2
-          err=1
-        else
-          echo "Replacing \${$var} with env var LIQUIBASE_$var value '$val'" >&2
-          contents=${contents//$varmatch/$val}
-          #val_esc=${val//$/\\$}
-          #val_esc=${val//{/\\{}
-          #val_esc=${val_esc//\}/\\\}}
-          #echo "ESCAPED: $val_esc"
-          #sed -i 's/\${'${var}'}/'${val_esc}'/g' liquibase.properties
-        fi
-      fi
-    done
-    if [[ "$err" -ne 0 ]]; then
-      if [[ "$contents" ==  *'${'*'}'* ]]; then
-        echo "Unrecognized replacement variable \${...} in liquibase.properties" >&2
-        err=1
-      fi
-    fi
-    if [[ "$err" -ne 0 ]]; then
-      echo "liquibase.properties contents before processing:" >&2
-      echo "$contents_orig" >&2
-      echo "liquibase.properties contents after processing:" >&2
-      echo "$contents" >&2
-    fi
-    echo "$contents" > liquibase.properties
+  Replaces any ${VAR} in a file with the environment variable VAR.
+
+OPTIONS:
+
+  --passes N        Number of times to re-process the file (this allows vars
+   -p N             to reference other vars in their values)
+
+  --prefix STRING   Prefix to limit replacements, if set to 'DB_' then only
+   -p STRING        environment variables beginning with DB_ will be
+                    replaced.  In the example DB_ case, ${USER} will be
+                    substituted with the environment variable DB_USER.
+
+  --strict          Fail if there are variables specified in the file which
+   -s               are not set in the environment. Default behavior is to
+                    replace with a blank string.
+
+  --verbose         Verbose mode, describe all replacements
+   -v
+
+  --help            Show usage information
+   -h
+
+EOF
+  exit $exit_code
+}
+
+export passes=2
+export file=''
+export verbose=0
+export strict=0
+export prefix=''
+
+while [[ "${1:-NULL}" != 'NULL' ]]; do
+  case "$1" in
+    -p|--passes)  passes="$2"; shift; shift ;;
+    -x|--prefix)  prefix="$2"; shift; shift ;;
+    -v|--verbose) verbose=$(($verbose+1)); shift ;;
+    -s|--strict)  strict=1; shift ;;
+    -h|--help)    usage ;;
+    *)            if [[ -z "$file" && ! "$1" =~ '^\-' ]]; then
+                    file="$1"; shift
+                  else
+                    usage "Unrecognized parameter $1" 254
+                  fi ;;
+  esac
+done
+
+#echo "passes:  $passes"
+#echo "prefix:  $prefix"
+#echo "verbose: $verbose"
+#echo "strict:  $strict"
+#echo "file:    $file"
+
+if [[ -z "$file" ]]; then usage 'No file provided' 253; fi
+if [[ ! -e "$file" ]]; then echo "File $file not found" >&2; exit 1; fi
+
+function say() { (( "$verbose" )) && echo "$1"; }
+
+contents=$(cat $file)
+contents_orig="$contents"
+
+if [[ -z "$prefix" ]]; then
+  IFS=$'\n' vars=( $( printenv | cut -d = -f 1 ) )
+else
+  IFS=$'\n' vars=( $( printenv | cut -d = -f 1 | grep -e '^'$prefix ) )
+fi
+
+err=0
+for pass in {1..$passes}; do
+  if [[ "$contents" !=  *'${'*'}'* ]]; then
+    [[ "$pass" -eq 1 ]] && say "No variables to replace in file $file"
+    break
   fi
-  unset contents contents_orig vars err val var varmatch lvar
+  say "Replacing variables in $file (pass $pass)"
+  for env_var in "${vars[@]}"; do
+    replace_var='${'"$env_var"'}'
+    [[ ! -z "$prefix" ]] && replace_var='${'$( echo "$env_var" | sed "s/^$prefix//" )'}'
+    eval "val=\${$env_var:-NULL}"
+    if [[ "$contents" == *"$replace_var"* ]]; then
+      if [[ "$val" == 'NULL' ]]; then
+        if [[ "$strict" -ne 0 ]]; then
+          echo "$replace_var in $file, but environment variable $env_var was not set" >&2
+          err=$(($err+1))
+        else
+          say "Replacing $replace_var with blank (environment variable $env_var was not set)"
+          contents=${contents//$repace_var/}
+        fi
+      else
+        say "Replacing $replace_var with environment variable $env_var value '$val'"
+        contents=${contents//$replace_var/$val}
+      fi
+    fi
+  done
+done
+
+if [[ "$strict" -ne 0 && "$err" -eq 0 && "$contents" ==  *'${'*'}'* ]]; then
+  echo 'Unrecognized replacement variable ${...} in '"$file"
+  err=$(($err+1))
+fi
+
+if [[ "$verbose" -gt 1 ]]; then
+  echo "$file contents before varsubst processing:" >&2
+  echo "$contents_orig" | sed 's/^/    /g' >&2
+  echo "$file contents after varsubst processing:" >&2
+  echo "$contents" | sed 's/^/    /g' >&2
+fi
+
+[[ ! $strict || "$err" -eq 0 ]] && echo "$contents" >$file
+exit $err
 
